GRANT SELECT, INSERT, DELETE, UPDATE
ON ap.*
TO BJWiley23
IDENTIFIED BY 'Swim1212**';

ALTER USER 'BJWiley23' WITH SELECT, INSERT, DELETE, UPDATE;
GRANT SELECT, INSERT, DELETE, UPDATE
ON ap.*
TO BJWiley23
IDENTIFIED BY 'Swim1212**';

SELECT CURRENT_USER()